# Site settings
title: Bob Marriott
twitter_username: bmarriott
name: Bob Marriott

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://daedaluslost.blogspot.com/
 - title: GitHub
   url: https://github.com/bobdmarriott
# - title: StackOverflow
#   url: http://stackoverflow.com/users/258813/rhinds
 - title: DZone
   url: https://dzone.com/users/707797/bobdmarriott.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/bob-marriott-93b5332

#Any buzzword skills you want to include
skills:
 - Groovy
 - Spring MVC
 - Spring Boot
 - Gradle
 - Java
 - JPA
 - SQL
 - REST
 - Tech Architecture

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: http://automateddeveloper.blogspot.com/feeds/posts/default?alt=rss

#Work experience is required
roles:
 - title: Technologist
   start: Oct 2015
   end: Ongoing
   employer: Department for Work and Pensions
   description: Creating digital services for DWP
 - title: Lead Architect
   start: Sep 2010
   end: Oct 2015
   employer: Harvard Technology Ltd
   description: Designing IoT solutions for street lighting and smart cities
 - title: IT Consultant
   start: Feb 2010
   end: Aug 2010
   employer: Howells Associates
   description: Building financial services platform
 - title: Analyst Developer
   start: Feb 2009
   end: Dec 2009
   employer: Press Association
   description: Building media platform applications
 - title: Senior Developer
   start: Feb 2007
   end: Feb 2009
   employer: Retail Express Ltd
   description: Creating analytical application for retail market
 - title: Senior Developer
   start: Mar 2006
   end: Nov 2006
   employer: ebuyer.com
   description: Designing integrated stock and billing systems
 - title: Senior Analyst Developer
   start: Apr 2003
   end: Mar 2006
   employer: RWE Systems UK
   description: Creating billing platform for utilities market
 - title: Analyst Developer
   start: Jun 2002
   end: Apr 2003
   employer: Sweet and Maxwell
   description: Designing editorial applications for legal publishers
 - title: Developer
   start: Sep 2001
   end: Apr 2002
   employer: Kingston Communications Ltd
   description: Building Europe's first streaming television service
 - title: E-Commerce Team Leader
   start: Jan 2000
   end: Sep 2001
   employer: Aviva
   description: Designing e-commerce protocols and applications for pensions market
 - title: Software Developer
   start: Jan 1998
   end: Dec 1999
   employer: University of York
   description: Created university admissions application
 
#Education is required
education:
 - level: Master of Science (M.Sc.)
   date: 1997
   subject: Computer Science
   school: University of Hatfield
 - level: Bachelor of Science (B.Sc.)
   date: 1996
   subject: Mathematics (with a year in Germany)
   school: University of York

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks.
